export type { INews } from "./INews"
export type { IResponse } from "./IResponse"
export type { IGetNewsParams } from "./IGetNewsParams"
export type { INewsInitialValues } from "./INewsInitialValues"
export type { IDeleteNewsResponse } from "./IDeleteNewsResponse"
