export type { INovelty } from "./INovelty"
export type { IResponse } from "./IResponse"
export type { IGetNewsParams } from "./IGetNewsParams"
export type { INoveltyInitialValues } from "./INoveltyInitialValues"
export type { IDeleteNewsResponse } from "./IDeleteNewsResponse"
